const yargs = require('yargs/yargs')
const { hideBin } = require('yargs/helpers')
const argv = yargs(hideBin(process.argv))
  .usage('Usage: $0 [OPTIONS]')
  .alias('h', 'help').describe('h', 'Show help')
  .alias('s', 'server').describe('s', 'Location of the Postgre database')
  .alias('p', 'port').describe('p', 'Port of the Postgre database')
  .alias('u', 'user').describe('u', 'User to access the database')
  .alias('k', 'password').describe('k', 'Password for the database user')
  .alias('d', 'database').describe('d', 'Database name in the server')
  .alias('i', 'install').describe('i', 'Install database schema (default false, TBI)').boolean('i')
  .alias('v', 'version')
  .demandOption(['server', 'port', 'user', 'password', 'database'])
  .epilog('That\'s all folks!')
  .argv
console.log(argv)
